#
# Parameters
#

IMAGE='exam-21-5-NMb.img'

# Disk parameters
BLOCK_SIZE=512
BLOCK_COUNT=768

# FAT12 parameters
NUMBER_OF_FATS=2
VOLUME_NAME='21NMB'
ROOT_DIR_SIZE=512
SECTORS_PER_CLUSTER=1

# Disk contents
NUMBER_OF_DIRECTORIES=8
NUMBER_OF_FILES_PER_DIRECTORY=8
NUMBER_OF_BYTES_PER_FILE=2411
