#
# Parameters
#

IMAGE='exam-21-5-VMa.img'

# Disk parameters
BLOCK_SIZE=256
BLOCK_COUNT=2048

# FAT12 parameters
NUMBER_OF_FATS=2
VOLUME_NAME='21VMA'
ROOT_DIR_SIZE=512
SECTORS_PER_CLUSTER=1

# Disk contents
NUMBER_OF_DIRECTORIES=8
NUMBER_OF_FILES_PER_DIRECTORY=8
NUMBER_OF_BYTES_PER_FILE=1221
