#
# Parameters
#

IMAGE='exam-21-5-VMb.img'

# Disk parameters
BLOCK_SIZE=1024
BLOCK_COUNT=384

# FAT12 parameters
NUMBER_OF_FATS=1
VOLUME_NAME='21VMB'
ROOT_DIR_SIZE=128
SECTORS_PER_CLUSTER=1

# Disk contents
NUMBER_OF_DIRECTORIES=8
NUMBER_OF_FILES_PER_DIRECTORY=8
NUMBER_OF_BYTES_PER_FILE=4659
