#
# Parameters
#

IMAGE='exam-21-5-NMa.img'

# Disk parameters
BLOCK_SIZE=512
BLOCK_COUNT=512

# FAT12 parameters
NUMBER_OF_FATS=2
VOLUME_NAME='21NMA'
ROOT_DIR_SIZE=256
SECTORS_PER_CLUSTER=2

# Disk contents
NUMBER_OF_DIRECTORIES=8
NUMBER_OF_FILES_PER_DIRECTORY=8
NUMBER_OF_BYTES_PER_FILE=1221
